### ISSUE TITLE
Error when starting from scratch: CreationException: Unable to create injector, see the following errors:

### ISSUE THREAD

**Issue by adis-me** [flyway/flyway-play#16]
Every time when I change one of my models and Play wants to re-apply the evolutions scripts I get the following error:

```
1) Error injecting constructor, @6mm01i5n4: Database 'default' needs migration!
  at org.flywaydb.play.PlayInitializer.<init>(PlayInitializer.scala:31)
  at org.flywaydb.play.PlayModule.bindings(PlayModule.scala:24):
Binding(class org.flywaydb.play.PlayInitializer to self eagerly) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1)
  while locating org.flywaydb.play.PlayInitializer
Caused by: @6mm01i5n4: Database 'default' needs migration!
	at org.flywaydb.play.PlayInitializer$$anonfun$org$flywaydb$play$PlayInitializer$$checkState$1.apply(PlayInitializer.scala:104)
	at org.flywaydb.play.PlayInitializer$$anonfun$org$flywaydb$play$PlayInitializer$$checkState$1.apply(PlayInitializer.scala:101)
	at scala.Option.foreach(Option.scala:257)
...
``` 

What am I doing wrong, I would like to apply the generated .sql from Play and let Flyway run the scripts afterwards..

**Comment by derfWayne** [comment]
Did you ever solve this problem?
